### ISSUE TITLE
ID Tag senden

### ISSUE THREAD

**Issue by MoonlanderPi** [foxriver76/ioBroker.ocpp#13]
Guten Morgen

Meine WB scheint zum ändern der Werte immer den IDTag zu benötigen.
Soweit ich das im Debug sehe, wird Standartmäßig die "1" mitgesendet.
Ich müsste aber den Tag von meiner RFID Karte mitsenden.
Ist es möglich diesen irgendwo einzufügen?

**Comment by foxriver76** [comment]
Kann ich gerne einbauen sobald ich Zeit finde.

**Comment by MoonlanderPi** [comment]
Ich glaube ich hab es schon geschafft. 
sieht jetzt so aus

`Sending RemoteStartTransaction for /: {"connectorId":1,"idTag":"C7131506","chargingProfile":{"chargingProfileId":1,"……….`

**Comment by foxriver76** [comment]
In 0.5.0 kann der idTag für jede Wallbox über den write-only state `wallboxName.idTag` gesetzt werden.
