### ISSUE TITLE
Unterdrücke führende Schrägstriche

### ISSUE THREAD

**Issue by FlorianSchulze** [foxriver76/ioBroker.ocpp#17]
Die angelegten Verzeichnisse für die Ladestation beginnen mit einem "/" - das verhindert die Verarbeitung zum Beispiel in node-red, dort werden diese nodes nicht geschaltet. Entweder sollten diese führenden dashes (und andere Sonderzeichen) unterdrückt werden oder -- noch besser und kompatibel mit bisherigen Installationen - es sollte einen config-schalter geben, mit dem dieses Verhalten geschaltet werden kann.

Beispiel für einen solchen Ordner, siehe "name": 
{
  "type": "device",
  "common": {
    "name": "/ABL-10115184"
  },
  "native": {
    "chargePointVendor": "ABL",
    "chargePointModel": "3W2264",
    "chargePointSerialNumber": "10115***",
    "chargeBoxSerialNumber": "10097***",
    "firmwareVersion": "1.8p2",
    "commandOcpp": "BootNotification"
  },
  "from": "system.adapter.ocpp.0",
  "user": "system.user.admin",
  "ts": 1665172706***,
  "_id": "ocpp.0./ABL-10115184",
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by foxriver76** [comment]
Ich kenne node-red nicht, gehe allerdings davon aus dass die Integration via einem Adapter abläuft. Solange slashes valide ids sind, sollte der Node-red Adapter damit umgehen können, ansonsten sollten slashes allgemein nicht erlaubt sein.

**Comment by foxriver76** [comment]
@Apollon77 opinion?

**Comment by Apollon77** [comment]
Puuhhh schwierig. Das Problem ist das einige Adapter für dich verbotene Zeichen haben. Slashes gegen auch bei MQTT kaputt Bzw werden ersetzt. 

Bei Node-Red auch oft MQTT like Strukturen genutzt, wo das jetzt aber exakt kaputt gehen kann weiß ich nicht. Da bräuchte man mehr Infos. Bei node-red sollte es aber Möglichkeiten geben das zu umgehen oder?

Aber ja formal sind slashes erlaubt.

**Comment by FlorianSchulze** [comment]
<img width="592" alt="Screenshot 2022-10-08 at 12 40 04" src="https://user-images.githubusercontent.com/40965321/194703499-910d89ca-0c7b-4c96-a60a-d485f86b562e.png">
<img width="217" alt="Screenshot 2022-10-08 at 12 41 10" src="https://user-images.githubusercontent.com/40965321/194703507-3d678472-c056-4902-9495-ab1b79aa6999.png">

Formal erlaubt, führen aber dauernd zu Fehlern und damit zu frustration und support. Ich hab´s mir lokal gepatcht, würde es aber im sinne einer einfachen Verbreitung des adapters nach dem motto "avoid known issues" vermeiden ;)

**Comment by Apollon77** [comment]
Ok, dann ist es eher ein Issue im node-red adapter das man slashes escapen kann wenn sie gewünscht sind. das dann bitte eher in node-red anlegen. Da ist es viel generischer als hier bei einem einzelnen Adapter :-)

**Comment by FlorianSchulze** [comment]
Das wäre "akademisch" richtig. Nur trifft es viele Adapter, node-red ist nur ein Beispiel. Homematic reagiert hier auch mit einem Fehler (hm-rpc).

**Comment by Apollon77** [comment]
hm-rpci reagiert mit einem Fehler? Was genauist gemeint?

**Comment by Apollon77** [comment]
Und "Akademisch" ist relativ. Fakt ist das ein "/"/ ein erlaubtes Zeichen ist in einer Objekt-ID. Wenn also ausgewählte Adapter damit probleme haben dann müssen die das fixen ... sorry ... Das ganze zu ändern und das "/" zu verbieten ist eine größere Nummer die eine unbekannte Zahl Adapter und vor allem ggf viele User-Skripte betreffen würde! Die betroffenene Adapter zufixen ist ggf das kleinere Übel
