### ISSUE TITLE
RFID Nummer in den idTag schreiben

### ISSUE THREAD

**Issue by fL4sH3r** [foxriver76/ioBroker.ocpp#21]
Moin @foxriver76,
könntest du einmal prüfen, ob man die RFID-Nummer auch in den idTag schreiben kann? 
Ich habe aktuell 3 RFID-Chips im Einsatz und die Anzahl der Zeichen sind ca. 14-15.

Hier ist der Auszug aus dem Log:
```

ocpp.0 | 2023-01-16 21:06:21.227 | debug | {"idTag":"XXXXXXXXXXXXXX","commandOcpp":"Authorize"}
ocpp.0 | 2023-01-16 21:06:15.845 | info | Received Status Notification from "/TACW1142021G1020.1": SuspendedEVSE
ocpp.0 | 2023-01-16 21:06:15.845 | debug | "connectorId":1,"errorCode":"NoError","info":"null","status":"SuspendedEVSE","vendorErrorCode":"0x0000","commandOcpp":"StatusNotification"}
ocpp.0 | 2023-01-16 21:06:15.345 | info | Received Start transaction from "/TACW1142021G1020.1"
ocpp.0 | 2023-01-16 21:06:15.345 | debug | {"connectorId":1,"idTag":"XXXXXXXXXXXXXX","meterStart":0,"timestamp":"2023-01-16T20:06:13.000Z","commandOcpp":"StartTransaction"}
```

**Comment by fL4sH3r** [comment]
Moin, hier ist ein Auszug von den idTags die der ioBroker schreibt und von meinen RFID-Chips.
![image](https://user-images.githubusercontent.com/97987283/213091535-ed2c63c7-f11d-401d-ae6d-b03fbfd65a1f.png)

Ich habe noch einen Fehler festgestellt. Bei der Ladung über einen RFID-Chip, ist es komischerweise egal ob der RFID-Chip in der Box registriert ist oder nicht. Man kann die Transaktion mit allen RFID-Chips starten und die Ladung beginnt. Obwohl in der Wallbox nur ein RFID-Chip autorisiert ist. 

Könntest du das bei Gelegenheit einmal prüfen?

**Comment by foxriver76** [comment]
Der `idTag` ist mit Absicht anders für die Remote Transaktionen, da klar unterscheidbar und lt. Standard so gewollt. Ich habe nun allerdings den random base64 string hinten entfernt in der GH Version, da der Tag zwar unique sein soll, allerdings sich natürlich nicht ständig wechseln soll, macht ja ein echter Tag auch nicht. 

Bzgl. der Liste habe ich mich etwas eingelesen. IMan kann die WB nicht initial auslesen, was dort hinterlegt ist. Man kann allerdings als OCPP Server, die Liste überschreiben. Ich könnte im Adapter im Kanal 0 einen State anlegen, der es erlaubt eine Liste von erlaubten ID Tags festzulegen, welche dann falls unterstützt (bei dir ist das so) auch lokal in der WB hinterlegt werden.

**Comment by fL4sH3r** [comment]
Die Unterscheidung vom idTag finde ich auch gut und das es zukünftig nur ioBroker heißt ebenfalls.
Die Idee mit Liste im Kanal 0 hört sich super an.
