### ISSUE TITLE
Problem with the Adapter Web Port

### ISSUE THREAD

**Issue by UserManualToRead** [foxriver76/ioBroker.ocpp#23]
Hello,
  
My Problem im not getting fixed is the Web port delivers a Upgrade Required when accessing. 
Further in the console of the Webbrowser it shows an error 426.

**Versions:**  
 - Adapter version: V0.12.5
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: Linux

**Comment by foxriver76** [comment]
The Adapter does Not Provide any Content on the Port it is just for the ocpp connection
