### ISSUE TITLE
index_m.html not found

### ISSUE THREAD

**Issue by ManuBT1** [foxriver76/ioBroker.ocpp#6]
Hello foxdriver76,

thanks for the development of the ocpp adaper !
Just wanted to test the adapter, unfortunately I only get the output "index_m.html not found" in the configuration.
Am I doing something wrong ? I have installed the adapter normally via npm.

Thanks
![20211103_103507603_iOS](https://user-images.githubusercontent.com/93650596/140045608-585b592d-3b3c-42d6-9d9a-78ffe7ef6e44.png)
 !

**Comment by foxriver76** [comment]
admin version?

**Comment by ManuBT1** [comment]
Admin 5.1.25

**Comment by foxriver76** [comment]
Then maybe you just need to upload, because it's not installed via iob. So `ìob upload ocpp` should fix it

**Comment by ManuBT1** [comment]
No, I have also completely reinstalled the adapter and tried "Upload". Still "not found
In the log is not much to see, the adapter itself seems to run
![20211103_110859609_iOS](https://user-images.githubusercontent.com/93650596/140050259-5e40d80c-cfda-46d3-b2cb-6f4bd5fabf66.png)
 !

**Comment by foxriver76** [comment]
Yes, adapter UI is based on JSON config which should be supported by your admin version afaik. Only thing which is configurable in the UI is the port of the server, so yes it runs on deafult port 9220.

**Comment by ManuBT1** [comment]
Thanks for the answer.
But I think I just do not understand the connection....
I can not configure anything in the adapter and when I call port 9220 I get now only "Update Required".

I guess that I am just the layer8 problem ! :-)

**Comment by foxriver76** [comment]
if you have an OCPP compatible wallbox, then you have to specify your ioBroker host ip and the selected port as OCPP server

**Comment by ManuBT1** [comment]
Thanks for the info ! I will try again tonight !

Super project !!!
