### ISSUE TITLE
Ergänzung der MeterValues ABB Terra AC

### ISSUE THREAD

**Issue by fL4sH3r** [foxriver76/ioBroker.ocpp#7]
Moin, nochmal danke für deine Tolle Arbeit. Könntest du bei Gelegenheit die MeterValues ergänzen?
Die Wallbox ist eine ABB Terra AC und diese Daten werden bereits aus dem ocpp Log mitgeliefert.

`2022-01-18 20:00:50.625	debug	{"connectorId":1,"transactionId":1,"meterValue":[{"timestamp":"2022-01-18T19:00:50.000Z","sampledValue":
[{"value":"229.60","context":"Sample.Periodic","format":"Raw","measurand":"Voltage","phase":"L1-N","unit":"V"},
{"value":"9.57","context":"Sample.Periodic","format":"Raw","measurand":"Current.Import","phase":"L1","unit":"A"},
{"value":"2170","context":"Sample.Periodic","format":"Raw","measurand":"Power.Active.Import","phase":"L1","unit":"W"},
{"value":"229.90","context":"Sample.Periodic","format":"Raw","measurand":"Voltage","phase":"L2-N","unit":"V"},
{"value":"9.54","context":"Sample.Periodic","format":"Raw","measurand":"Current.Import","phase":"L2","unit":"A"},
{"value":"2163","context":"Sample.Periodic","format":"Raw","measurand":"Power.Active.Import","phase":"L2","unit":"W"},
{"value":"232.40","context":"Sample.Periodic","format":"Raw","measurand":"Voltage","phase":"L3-N","unit":"V"},
{"value":"0.0","context":"Sample.Periodic","format":"Raw","measurand":"Current.Import","phase":"L3","unit":"A"},
{"value":"0","context":"Sample.Periodic","format":"Raw","measurand":"Power.Active.Import","phase":"L3","unit":"W"},
{"value":"176","context":"Sample.Periodic","format":"Raw","measurand":"Energy.Active.Import.Register","unit":"Wh"},
{"value":"10","context":"Sample.Periodic","format":"Raw","measurand":"Current.Offered","unit":"A"}]}],
"commandOcpp":"MeterValues"}`

**Comment by foxriver76** [comment]
Please test 0.3.0

**Comment by fL4sH3r** [comment]
Funktioniert einwandfrei. DANKE

![Screenshot_20220118-230644_Chrome](https://user-images.githubusercontent.com/97987283/150027636-506a7780-cd14-47a5-bfc5-aa68cce160a3.jpg)
